resources:
  repositories:
    - repository: templates
      type: github
      name: NSLS-II/profile-collection-ci
      ref: refs/heads/main
      endpoint: github

jobs:
  - template: 2024-2.3-py310.yml@templates
    parameters:
      beamline_acronym: SMI
  - template: 2024-2.3-py311.yml@templates
    parameters:
      beamline_acronym: SMI
  - template: 2024-2.3-py312-tiled.yml@templates
    parameters:
      beamline_acronym: SMI